# Generated by Django 4.2.1 on 2023-06-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('faculty', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
