# Generated by Django 4.2.1 on 2023-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.ImageField(default='./img/panda.jpg', upload_to='img'),
        ),
    ]
